### ISSUE TITLE
Could not install/find pod

### ISSUE THREAD

**Issue by unclesamer** [masahikot/CRToastSwift_Old#1]
I tried to install it via pod, but it does not work.

**Comment by masahikot** [comment]
Sorry this pod is currently in develop.
Please wait for v0.1 release (coming soon!) and then try again.

**Comment by masahikot** [comment]
v0.1.0 has been released.
You can now `pod try CRToastSwift`.

**[Note]**
This repository has been renamed to `CRToastSwift_Old` and a [new `CRToastSwift` repository](https://github.com/masahikot/CRToastSwift) has been created for some reasons.
From now, the project will be developed on the new repository, and the old one will be deleted in near future.
